### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by MeestorX** [LykaiosNZ/reaper-osc.js#32]
Does this library support marker functions? (Go to marker by name/number, add/delete/rename, etc.)?

**Comment by LykaiosNZ** [comment]
Not presently, see #17.

It should be pretty simple to add if you wanted to put in a PR, otherwise I will probably get it added in the next couple of weeks - my focus right now is getting the [companion module](https://github.com/bitfocus/companion-module-cockos-reaper) updated.

If you're interested in this feature for that please create an issue over there. In the meantime my fork has the `support-3.x` branch which supports sending custom messages, although it's still lacking other functionality I will probably get it up to parity with the current version over the coming weekend.

**Comment by MeestorX** [comment]
Cool. Thought I'd just check first.
Forked the Companion module to add some additional functionality that might be useful. I'll pr it when I have it working.
Thank you for doing this!
